Repository Sylius/Stack, pull requests merged in 2025-01, with the labels that each got.

#207 [Docs]: Twig Hooks composable layout fix typos
  docs/twig-hooks/composable-layouts-with-a-predictable-structure.md
Labels: documentation

#208 [TwigHooks] Template configuration provider with context
  config/packages/sylius_twig_hooks.yaml
  src/TwigHooks/config/services.php
  src/TwigHooks/config/services/hookable_renderer.php
  src/TwigHooks/src/Hookable/Metadata/HookableMetadata.php
  src/TwigHooks/src/Hookable/Renderer/HookableTemplateRenderer.php
  src/TwigHooks/src/Provider/TemplateConfigurationProvider.php
  src/TwigHooks/src/Provider/TemplateConfigurationProviderInterface.php
  src/TwigHooks/tests/Unit/Hookable/Renderer/HookableTemplateRendererTest.php
  src/TwigHooks/tests/Unit/Provider/TemplatesConfigurationProviderTest.php
  templates/book/show/content/page_body.html.twig
  tests/Functional/BookTest.php
  tests/Translations/FrenchTranslatedUiTest.php
Labels: feature

#210 [Docs] Customizing page title
  config/packages/sylius_twig_hooks.yaml
  docs/.gitbook/assets/browsing_speakers.png
  docs/.gitbook/assets/managing_speakers_subheader.png
  docs/.gitbook/assets/speakers_icon.png
  docs/cookbook/admin_panel/page_titles.md
  src/BootstrapAdminUi/templates/shared/helper/header.html.twig
  tests/Functional/BookTest.php
  tests/Functional/ConferenceTest.php
  tests/Functional/DashboardTest.php
  tests/Functional/SpeakerTest.php
  tests/Functional/TalkTest.php
  tests/Translations/FrenchTranslatedUiTest.php
  translations/messages.en.yaml
  translations/messages.fr.yaml
Labels: documentation

#212 Customize icons & subheaders on all CRUD pages
  config/packages/sylius_twig_hooks.yaml
  src/AdminUi/tests/Functional/.application/src/State/Provider/BookCollectionProvider.php
  src/AdminUi/tests/Functional/.application/src/State/Provider/BookItemProvider.php
  src/AdminUi/tests/Functional/TemplatesTest.php
  src/BootstrapAdminUi/templates/shared/crud/create/content/header/title_block/title.html.twig
  src/BootstrapAdminUi/templates/shared/crud/index/content/header/title_block/title.html.twig
  src/BootstrapAdminUi/templates/shared/crud/show/content/header/title_block/title.html.twig
  src/BootstrapAdminUi/templates/shared/crud/update/content/header/title_block/title.html.twig
  src/BootstrapAdminUi/tests/Functional/.application/src/Grid/Provider/BookGridProvider.php
  src/BootstrapAdminUi/tests/Functional/.application/src/State/Provider/BookItemProvider.php
  src/BootstrapAdminUi/tests/Functional/TemplatesTest.php
  tests/Functional/BookTest.php
  tests/Functional/ConferenceTest.php
  tests/Functional/LegacyBookTest.php
  tests/Translations/FrenchTranslatedUiTest.php
  translations/flashes.fr.yaml
  translations/messages.en.yaml
  translations/messages.fr.yaml
Labels: feature

#215 Fix too many hook prefixes
  src/AdminUi/templates/base.html.twig
Labels: bug

#224 [BootstrapAdminUi] Add boolean grid field
  src/BootstrapAdminUi/templates/shared/grid/field/boolean.html.twig
  src/BootstrapAdminUi/templates/shared/helper/field/boolean.html.twig
Labels: feature

#219 Init editor config
  .editorconfig
Labels: maintenance

#221 [Docs] Improve your first grid chapter
  docs/.gitbook/assets/grid.png
  docs/.gitbook/assets/grid_filters.png
  docs/.gitbook/assets/grid_full.png
  docs/.gitbook/assets/suppliers_grid.png
  docs/grid/your_first_grid.md
Labels: documentation

#225 [Docs][Resource] Warn about legacy section
  docs/resource/legacy/configuration.md
  docs/resource/legacy/create_resource.md
  docs/resource/legacy/delete_resource.md
  docs/resource/legacy/forms.md
  docs/resource/legacy/index.md
  docs/resource/legacy/index_resources.md
  docs/resource/legacy/reference.md
  docs/resource/legacy/routing.md
  docs/resource/legacy/services.md
  docs/resource/legacy/show_resource.md
  docs/resource/legacy/state_machine.md
  docs/resource/legacy/update_resource.md
Labels: documentation

#180 [Docs] Custom filter fix typos
  docs/SUMMARY.md
  docs/grid/custom_filter.md
  docs/grid/index.md
Labels: documentation

#181 [Docs] Custom field type reword / fix typos
  docs/SUMMARY.md
  docs/grid/custom_field_type.md
  docs/grid/index.md
Labels: documentation

#183 [Docs] Custom bulk action fix typo
  docs/SUMMARY.md
  docs/grid/custom_bulk_action.md
  docs/grid/index.md
Labels: documentation
